AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  crac-demo-java-magazin

Resources:
  JavaMagazinSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: JavaMagazinRDSSecrets

  JavaMagazinSnapStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Java-Magazin-Crac-Snapstart-Demo
      Handler: com.amazonaws.serverless.proxy.spring.SpringDelegatingLambdaContainerHandler
      Runtime: java21
      CodeUri: ./../target/serverless.jar
      MemorySize: 2048
      Timeout: 30
      AutoPublishAlias: SnapStart
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          MAIN_CLASS: com.exxeta.serverless.ServerlessApplication
          SPRING_DATASOURCE_HIKARI_ALLOW_POOL_SUSPENSION: true
          contextInitTimeout: 240000
          SPRING_DATASOURCE_PASSWORD: !Sub '{{resolve:secretsmanager:${JavaMagazinSecretsManager}::SPRING_DATASOURCE_PASSWORD}}'
          SPRING_DATASOURCE_URL: !Sub '{{resolve:secretsmanager:${JavaMagazinSecretsManager}::SPRING_DATASOURCE_URL}}'
          SPRING_DATASOURCE_USERNAME: !Sub '{{resolve:secretsmanager:${JavaMagazinSecretsManager}::SPRING_DATASOURCE_USERNAME}}'

  JavaMagazinGraalVMFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Java-Magazin-GraalVM-Demo
      Runtime: provided.al2023
      CodeUri: ./../graalvm-serverless.zip
      MemorySize: 512
      Handler: NOP
      Timeout: 30
      Architectures:
        - x86_64
      Environment:
        Variables:
          SPRING_DATASOURCE_PASSWORD: !Sub '{{resolve:secretsmanager:${JavaMagazinSecretsManager}::SPRING_DATASOURCE_PASSWORD}}'
          SPRING_DATASOURCE_URL: !Sub '{{resolve:secretsmanager:${JavaMagazinSecretsManager}::SPRING_DATASOURCE_URL}}'
          SPRING_DATASOURCE_USERNAME: !Sub '{{resolve:secretsmanager:${JavaMagazinSecretsManager}::SPRING_DATASOURCE_USERNAME}}'

  JavaMagazinApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: JavaMagazinApi
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        swagger: 2.0
        info:
          title: JavaMagazin API
          version: 1.0
        paths:
          /snapstart/{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
                - application/json
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JavaMagazinSnapStartFunction.Arn}:SnapStart/invocations
                passthroughBehavior: WHEN_NO_MATCH
                httpMethod: POST
                type: aws_proxy
                requestTemplates:
                  application/json: |
                    #set($path = $input.path('$').substring($input.path('$').indexOf('/snapstart') + 10))
                    {
                      "path": "$path
                    }
          /graalvm/{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
                - application/json
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JavaMagazinGraalVMFunction.Arn}/invocations
                passthroughBehavior: WHEN_NO_MATCH
                httpMethod: POST
                type: aws_proxy
                requestTemplates:
                  application/json: |
                    {
                      "body": $input.json('$'),
                      "pathParameters": {
                        #set($contextPath = "/graalvm")
                        #set($newPath = $input.params().path.get("proxy").substring($contextPath.length()))
                        "path": "$newPath"
                      }
                    }

  JavaMagazinSnapStartFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt JavaMagazinSnapStartFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${JavaMagazinApiGateway}/*/*/snapstart/*

  JavaMagazinSnapStartFunctionVersionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub ${JavaMagazinSnapStartFunction.Arn}:SnapStart
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${JavaMagazinApiGateway}/*/*/snapstart/*

  JavaMagazinGraalVMFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt JavaMagazinGraalVMFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${JavaMagazinApiGateway}/*/*/graalvm/*